id: I4ABB1A11
legacy_id: P004260
ocr_import_info:
  bdrc_scan_id: W10419
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T06:50:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T13:02:00.613344+00:00'
last_modified: 2022-08-29 21:04:04.671364
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W10419
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW10419
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ངོར་མཁན་ཆེན་དཔལ་ལྡན་ཆོས་སྐྱོང་ཞབས་ཀྱི་རྣམ་ཐར། ༼སྡེ་དགེ་པར་མ་བསྐྱར་པར།༽
  author: ཞུ་ཆེན་ཚུལ་ཁྲིམས་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.7716604987607235
  ocr_word_median_confidence_index: 0.8399999737739563
quality: null
bases:
  I3191:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3191
      total_pages: 442
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3191.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7624322142960205
    legacy_id: v003
  I3193:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3193
      total_pages: 480
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3193.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8217546894043208
    legacy_id: v007
  I3192:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3192
      total_pages: 518
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3192.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7724879717776745
    legacy_id: v005
  I3190:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3190
      total_pages: 406
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3190.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.7228121938519241
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
