id: I4ABB1A11
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T06:54:03+00:00'
last_modified: '2022-06-07T21:29:33.128698+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W10419
  title: ངོར་མཁན་ཆེན་དཔལ་ལྡན་ཆོས་སྐྱོང་ཞབས་ཀྱི་རྣམ་ཐར། ༼སྡེ་དགེ་པར་མ་བསྐྱར་པར།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F923:
      image_group_id: I3190
      title: ''
      total_pages: 406
      order: 1
      base_file: F923.txt
    '6240':
      image_group_id: I3191
      title: ''
      total_pages: 442
      order: 3
      base_file: 6240.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
